First attempt at setting up docker-compose stack.
dev-homies/first-project pull request #23
Opened 2022-07-17 20:21 UTC by zelnaut

2022-07-21 21:59 UTC, QuickFinesse commented on api/main.go
> -		AllowOrigins:     []string{"http://localhost:3000", "http://localhost:4000"},
I had to add this back to `AllowOrigins:     []string{"http://localhost:3000", "http://localhost:4000"},` to get it to work in Windows

2022-07-21 22:00 UTC, QuickFinesse commented on api/main.go
> +		AllowOrigins:     []string{"*"},
I had to add this back to the code below to get it to work in Windows
```suggestion
		AllowOrigins:     []string{"http://localhost:3000", "http://localhost:4000"},
```

2022-07-21 22:01 UTC, QuickFinesse requested changes
Works fucking great! Only thing is  the cors error I updated below. You'll have to double check that works on your mac or linux whatever you're using

2022-07-22 09:33 UTC, zelnaut commented on api/main.go
> +		AllowOrigins:     []string{"*"},
Just tried it out again locally, for some reason it works fine through Firefox, but not Chrome :shrug:

2022-07-23 17:31 UTC, QuickFinesse approved these changes
👍

2022-07-23 17:33 UTC, merged